---
id: a36d1abe-60f0-44ea-b9bd-e5147e5d4448
---

# 异步

## 异步编程

### 异步和同步

**同步**

- 严格按照顺序执行;

**异步**

- 不按照顺序, 各自执行;

**原始实现异步**

```typescript
// 通过 setTimeout() 和回调函数
// setTimeout() 会将函数推送到宏任务消息队列中;
// 失败和成功回调函数单独定义
// 容易产生可怕的回调地狱
function double(value, success, failure) {
  setTimeout(() => {
    try {
      success(2 * value);
    } catch (e) {
      failure(e);
    }
  }, 1000);
}
const successCallback = (x) => {
  double(x, (y) => console.log(`Success: ${y}`));
};
const failureCallback = (e) => console.log(`Failure: ${e}`);
double(3, successCallback, failureCallback); // Success: 12（大约 1000 毫秒之后
```

## promise

### 基础

**定义 promise**

```typescript
// promise 为同步对象, 但也是连接异步对象的媒介
// promise 创建即使用
// pending, resolve 和 rejected 三种状态, 分别为执行中, 执行成功, 执行失败
// pending 表示正在或者等待执行
// resolve() 和 reject() 表明 promise 执行内部代码后要进入失败或成功状态
// resolve() 和 reject() 并不会使 promise 直接进入成功或失败状态. 而是执行完函数代码后进入对应状态
let p1 = new Promise((resolve, reject) => resolve());
let p2 = new Promise((resolve, reject) => reject());
```

**使用 promise**

```typescript
// promise 只能切换一次状态
let p = new Promise((resolve, reject) => {
  setTimeout(reject, 10000);
  // ...
});
p.then(null, () => onRejected(p));

// 默认初始状态为 pending
// 可切换初始状态, 下面两者为幂等方法
let p1 = Promise.reject(1);
let p2 = Promise.resolve(1);
// Promise.reject() 和 Promise.resolve() 与下述代码等效
let p1 = new Promise((resolve, reject) => resolve(1));
let p2 = new Promise((resolve, reject) => reject(1));
```

**同步异步的二元性**

```typescript
// 同种模式的代码可以相互执行;
// 不同种模式的代码无法相互执行;
try {
  Promise.reject(new Error("bar"));
} catch (e) {
  console.log(e);
}
// Uncaught (in promise) Error: bar
```

### 特性

**非重入特性**

```typescript
// promise 切换状态后, 其对应处理程序进入微任务消息队列
// promise 后的同步代码一定在其执行之前完成
let p1 = Promise.resolve();
p1.then(() => console.log("p1.then() onResolved"));
console.log("p1.then() returns");
let p2 = Promise.reject();
p2.then(null, () => console.log("p2.then() onRejected"));
console.log("p2.then() returns");
// p1.then() returns
// p2.then() returns
// p1.then() onResolved
// p2.then() onRejected
```

**多个处理程序的执行顺序**

```typescript
// 根据代码顺序执行
let p1 = Promise.resolve();
p1.then(() => setTimeout(console.log, 0, 1));
p1.then(() => setTimeout(console.log, 0, 2));
// 1
// 2
```

**解决值和拒绝理由**

```typescript
// 解决值和拒绝理由作为箭头的第一个参数, onResolved 和 onRejected 的唯一参数
let p1 = new Promise((resolve, reject) => resolve("foo"));
p1.then((value) => console.log(value)); // foo
let p2 = new Promise((resolve, reject) => reject("bar"));
p2.catch((reason) => console.log(reason)); // bar
```

**错误处理**

```typescript
// Promise 的错误处理, 只能通过异步的 onRejected 捕获;
// 不能使用 trow, 否则报错
// promise 代码报错导致 rejected 状态
let p = new Promise((resolve, reject) => {
  throw Error("foo");
}); // Promise <rejected>: Error: foo
Promise.reject(Error("foo")).catch((e) => {});

// promise 报错, 在其后的同步代码执行后才会抛出错误
Promise.reject(Error("foo"));
console.log("bar");
// bar
// Uncaught (in promise) Error: foo

// catch 正确处理错误后返回一个 resolved 状态的 promise
new Promise((resolve, reject) => {
  console.log("begin asynchronous execution");
  reject(Error("bar"));
})
  .catch((e) => {
    console.log("caught error", e);
  })
  .then(() => {
    console.log("continue asynchronous execution");
  });
// begin asynchronous execution
// caught error Error: bar
// continue asynchronous execution
```

### 期约连锁

**期约连锁**

```typescript
// promise 返回一个新的 Promise, 连锁使用;
let p = new Promise((resolve, reject) => {
  console.log("first");
  resolve();
});
p.then(() => console.log("second"))
  .then(() => console.log("third"))
  .then(() => console.log("fourth"));
// first
// second
// third
// fourth
```

**串行化异步任务**

```typescript
// 后续 promise 等待前一 promise 执行完毕
let p = new Promise((resolve, reject) => {
  console.log("initial promise rejects");
  reject();
});
p.catch(() => console.log("reject handler"))
  .then(() => console.log("resolve handler 1"))
  .then(() => console.log("resolve handler 2"))
  .finally(() => console.log("finally handler"));
// initial promise rejects
// reject handler
// resolve handler 1
// resolve handler 2
// finally handler
```

**期约图**

```typescript
// 下级节点会在上级节点完成后执行
// 执行顺序结合上级节点和下级节点的代码顺序
// 与二叉树的前序排列机制一致
//     A
//    / \
//   B   C
//  /\   /\
// D  E F  G
let A = new Promise((resolve, reject) => {
  console.log("A");
  resolve();
});
let B = A.then(() => console.log("B"));
let C = A.then(() => console.log("C"));
C.then(() => console.log("F"));
C.then(() => console.log("G"));
B.then(() => console.log("D"));
B.then(() => console.log("E"));
// A B C D E F G
```

### 期约合成

**基本方法**

- 使用 race 和 all 静态方法;

**串行期约合成**

```typescript
function addTwo(x) {
  return x + 2;
}
function addThree(x) {
  return x + 3;
}
function addFive(x) {
  return x + 5;
}
function addTen(x) {
  return Promise.resolve(x).then(addTwo).then(addThree).then(addFive);
}
addTen(8).then(console.log); // 18
```

### 期约拓展

**期约取消**

```typescript
function cancellableDelayedResolve(delay) {
  setTimeout(console.log, 0, "set delay");
  return new Promise((resolve, reject) => {
    const id = setTimeout(() => {
      setTimeout(console.log, 0, "delayed resolve");
      resolve();
    }, delay);
    const cancelToken = new CancelToken((cancelCallback) =>
      cancelButton.addEventListener("click", cancelCallback)
    );
    cancelToken.promise.then(() => clearTimeout(id));
  });
}
```

**期约通知**

```typescript
class TrackablePromise extends Promise {
  constructor(executor) {
    const notifyHandlers = [];
    super((resolve, reject) => {
      return executor(resolve, reject, (status) => {
        notifyHandlers.map((handler) => handler(status));
      });
    });
    this.notifyHandlers = notifyHandlers;
  }
  notify(notifyHandler) {
    this.notifyHandlers.push(notifyHandler);
    return this;
  }
}
```

### 常用 API

**resolve()**

```typescript
// 两者等效
const p1 = Promise.resolve(123);
const p2 = new Promise((resolve, reject) => {
  resolve(123);
});
// 参数若为值, 返回值为 123 的 resolved 状态的 promise
const p1 = Promise.resolve(123); //
// 参数若为 promise, 返回 p1 本身
const p2 = Promise.resolve(p1);
```

**reject()**

```typescript
// 两者等效
const p1 = Promise.reject(123);
const p2 = new Promise((resolve, reject) => {
  reject(123);
});
// 参数若为值, 返回值为 123 的 rejected 状态的 promise
const p1 = Promise.resolve(123); //
// 参数若为 promise, 返回新的与 p1 等效的 promise
const p2 = Promise.resolve(p1); // p1 和 p2 不是一个实例
```

**then()**

```typescript
const p1 = new Promise((resolve, reject) => {
  // ...
});
// 在 p1 进入对应的 resolve 或 reject 状态时, 解包 p1 返回的 promise 值作为第一个参数
// 立刻返回一个新的与 p1 等效的 pending 状态的 promise 实例
// 若不报错返回一个与 p1 等效的的 resolved 状态的 promise 的实例, 反之返回 rejected 状态的 promise 实例
// onFulfilled 省略使用 (x) => x 替换
// onRejected 省略 使用 (x) => throw x 替换
p1.then(
  (value) => {
    // resolve
    console.log(value);
  },
  (reason) => {
    // reject
    console.error(reason);
  }
);

// 返回一个值为 1 的 resolved 状态的 promise
p1.then((value) => 1);
// 返回一个值为 undefined 的 resolved 状态的 promise
p1.then((value) => {});
// 返回一个值为 123 的 resolved 状态的 promise
p1.then((value) => Promise.resolve(123));
// 返回一个值为 123 的 rejected 状态的 promise
p1.then((value) => Promise.reject(123));
```

- Promise.prototype.then((value) => {// fulfillment handler},(reason) => {// rejection handler}): Promise 静态方法;
  - 在 promise 进入对应的 resolve 或 reject 状态时, 执行对应代码;
  - 立刻返回一个新的 pending 状态的等价的 Promise 实例;
  - 若不报错最终返回一个新的 resolved 状态的等价的 promise, 反之返回报错生成的 rejected 状态的 promise;
- Promise.prototype.catch(catch((reason) => {// rejection handler})): Promise 静态方法;
  - Promise.prototype.then(null, onRejected) 的语法糖;
  - 立刻返回一个新的 pending 状态的等价的 Promise 实例;
  - 若不报错最终返回一个新的 resolved 状态的等价的 promise, 反之返回报错生成的 rejected 状态的 promise;
- Promise.prototype.finally(() => {// Code that will run after promise is settled}): Promise 静态方法;
  - 无论状态如何都会执行;
  - 若不报错最终返回一个新的 resolved 状态的等价的 promise, 反之返回报错生成的 rejected 状态的 promise;
- Promise.all(iterable): Promise 静态方法;
  - 合成 iterable 中的所有 promise, 在其所有的 promise 解决后再返回解决;
  - 所有 promise 异步计算;
  - 如果其中一个 promise 待定或者拒绝, 返回相同状态的 promise;
    - 第一个拒绝的 promise 作为拒绝理由, 其余 promise 静默处理;
  - 若全部解决, 返回 iterable 的解决值数组;
- Promise.race(iterable): Promise 静态方法;
  - 返回 iterable 中第一个解决或拒绝的 promise 的镜像;
  - 其余 promise 静默处理;

## async/await

### async

**声明 async**

```typescript
// 声明异步
let bar = async function () {};
let baz = async () => {};
```

**返回值**

```typescript
// 立刻返回一个 pending 状态的 Promise
// 代码运行成功为 resolved 状态
// 代码报错为 rejected 状态
async function foo() {
  console.log(1);
  return 3;
}
foo().then(console.log);
console.log(2);
// 1
// 2
// 3
// 拒绝期约的错误不会被异步函数捕获
async function foo() {
  console.log(1);
  Promise.reject(3);
  console.log(4);
}
// Attach a rejected handler to the returned promise
foo().catch((error) => console.log(error));
console.log(2);
// 1
// 4
// 2
// Uncaught (in promise): 3
```

### await

**声明 await**

```typescript
async function baz() {
  await new Promise((resolve, reject) => setTimeout(resolve, 1000));
  console.log("baz");
}
baz();
// baz（1000 毫秒后）
```

**await 机制**

- 首先暂停异步函数;
- 其次执行 await 后的表达式中的同步代码;
- 接着执行其余的同步代码;
- 直至表达式返回值可用, 向微服务消息队列推送一个恢复异步函数其余代码执行的任务;
- await 获取表达式的值;
- 恢复异步函数执行;

```typescript
async function foo() {
console.log(2);
console.log(await null);
console.log(4);
}
console.log(1);
foo();
console.log(3);
// 打印 1
// 调用 foo()
// 打印 2
// 遇到 await, 暂停 foo(), 执行 null, 立刻返回可用的值, 为其向消息队列添加一个任务
// 打印 3
// await 获得 null, 恢复异步函数执行
// 打印 null
// 打印 4
```

**返回值**

```typescript
// await 会解包 promise, 即 then() 中的 result
// 若返回对象不是 promise, 视其为已经解决的期约
async function foo() {
console.log(await 'foo');
}
foo();
// foo
async function qux() {
console.log(await Promise.resolve('qux'));
}
qux();
// qux

// 拒绝期约的错误不会被异步函数捕获, 但对其使用 await 会被异步函数捕获
async function foo() {
  console.log(1);
  await Promise.reject(3); // 解包 promise
  console.log(4); // 不会执行
}
foo().catch((error) => console.log(error));
console.log(2);
// 1
// 2
// 3
```

**await 的限制**

```typescript
// 只能在 async 函数中使用
async function foo() {
  console.log(await Promise.resolve(3));
}

// async 不会拓展到内部嵌套函数
function foo() {
  const syncFn = () => {
    return await Promise.resolve("foo");
  };
}
```

**await 的作用**

```typescript
// 若不使用 await, async 和普通函数没有区别
async function foo() {
  console.log(2);
}
console.log(1);
foo();
console.log(3);
// 1
// 2
// 3
```

### 异步函数进阶

**代码执行顺序**

```typescript
const foo = async () => {
  const bar = async () => {
    console.log("bar");
  };
  console.log("bar before");
  await bar().then(() => {
    console.log("bar then");
  });
  console.log("bar after");
};
const main = async () => {
  console.log("foo before");
  foo().then(() => {
    console.log("foo then");
  });
  console.log("foo after");
};
main();
// 执行 main()
// 打印 foo before
// 执行 foo()
// 打印 bar before
// 遇到 await, 暂停 foo(), 执行 bar()
// 执行 bar() 中的同步代码, 打印 bar
// bar() 执行完毕, 立刻返回 resolve 状态的 promise, 退出 bar()
// await 获取到 bar() 的返回值, 向微服务消息队列推送一个恢复 foo() 异步函数执行的任务
// 退出 foo()
// 打印同步代码 foo after
// 同步代码执行完成
// 恢复 foo() 异步函数执行
// 执行 bar().then(), 打印 bar then
// 打印 bar after
// foo() 返回 resolve 状态的 promise, 退出 bar()
// 执行 foo().then(), 打印 foo then

const async1 = async () => {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
};
const async2 = () => {
  console.log("async2");
};

console.log("script start");
setTimeout(() => {
  console.log("setTimeout");
}, 0);
async1();
new Promise((resolve) => {
  console.log("promise1");
  resolve(1);
  console.log("resolve after");
}).then(() => {
  console.log("promise2");
});
console.log("script end");
// 打印 script start
// 执行 setTimeout(), 将其推送至宏任务消息队列
// 执行 async1()
// 打印 async1 start
// 遇到 await, 暂停 async1(), 执行 async2()
// 执行 async2() 中的同步代码, 打印 async2
// async2() 执行完毕, 返回 resolved 状态的 promise, 退出 async2()
// await 获取 async2() 的返回值, 向微服务消息队列推送一个恢复 async1() 执行的任务
// 退出 async1()
// 进入 Promise
// 打印 promise1
// 执行 resolve(1), 切换 promise 状态为 resolved
// 打印 resolve after
// 执行 promise.then(), 将其推送至微服务消息队列
// 打印 script end
// 同步代码执行完成
// 恢复 async1() 执行, 打印 async1 end
// 执行 promise.then(), 打印 promise2
// 执行 setTimeout(), 打印 setTimeout

const sleep = async () => {
    return new Promise((resolve) => {
      console.log("sleep before")
      setTimeout(resolve, 1000)
    }).then(()=>{console.log("sleep after")})
}
const fn = async () => {
    console.log('fn')
    await sleep()
    return null
}
async function foo() {
    console.log(2);
    console.log(await fn());
    console.log(4);
}
console.log(1);
foo().then(() => console.log('end'));
console.log(3);
// 打印 1
// 进入 foo()
// 打印 2
// 遇到 await, 暂停 foo() 执行, 执行 fn()
// 执行 fn() 中的同步代码, 打印 in
// 遇到 await, 暂停 fn(), 执行 sleep()
// 执行 sleep() 中的同步代码
// 打印 sleep before
// 执行 setTimeout(), 将其推送至宏任务消息队列
// 打印 sleep after
// fn 中的 await 等待 sleep() 返回的可用值, 退出 fn()
// foo 等待 fn() 返回的可用值, 退出 foo()
// 打印 3
// 1s 后, 恢复 setTimeout() 执行, 返回 resolved 状态的 promise
// 执行 sleep() 函数中的 then(), 打印 sleep after, 返回值为 null 的 resolved 状态的 promise
// fn() 中的 await 接受到 sleep() 的可用值, 向消息队列返回一个恢复 fn() 执行的任务
// 恢复 fn() 执行
// 打印 null
// 打印 4
// 返回值为 undefined 的 resolved 状态的 promise
// 执行 foo().then(), 打印 end
```

**实现 sleep()**

```typescript
async function sleep(delay) {
  return new Promise((resolve) => setTimeout(resolve, delay));
}
async function foo() {
  const t0 = Date.now();
  await sleep(1500); // 暂停约 1500 毫秒
  console.log(Date.now() - t0);
}
foo();
// 1502
```

**串行执行期约**

```typescript
async function addTwo(x) {
  return x + 2;
}
async function addThree(x) {
  return x + 3;
}
async function addFive(x) {
  return x + 5;
}
async function addTen(x) {
  for (const fn of [addTwo, addThree, addFive]) {
    x = await fn(x);
  }
  return x;
}
addTen(9).then(console.log); // 19
```

### 疑难杂症

**循环中的异步**

```typescript
// array 的 foreach() 方法回调函数中 await 无效;
files.forEach(async (file) => {
  const contents = await fs.readFile(file, "utf8");
  console.log(contents);
});
// 可使用 for, for of 循环替代;
for (const file of files) {
  const contents = await fs.readFile(file, "utf8");
  console.log(contents);
}
// map 中 await 有效, 且总是返回 promise 数组
// 建议不要在 filter 和 reduce 中使用 await
```
